=== jbcedeno930806/multiband/build/lib/netsim/netSimPy/filemanager/network.schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "default": {},
    "title": "Root Schema",
    "required": [
        "alias",
        "Name",
        "nodes",
        "bands_info",
        "links"
    ],
    "properties": {
        "alias": {
            "type": "string",
            "default": "",
            "title": "The alias Schema"
        },
        "Name": {
            "type": "string",
            "default": "",
            "title": "The Name Schema"
        },
        "nodes": {
            "type": "array",
            "default": [],
            "title": "The nodes Schema",
            "items": {
                "type": "object",
                "title": "A Schema",
                "required": [
                    "id"
                ],
                "properties": {
                    "id": {
                        "type": "integer",
                        "title": "The id Schema"
                    }
                }
            }
        },
        "bands_info": {
            "type": "object",
            "default": {},
            "title": "The bands_info Schema",
            "additionalProperties": {
                "type": "integer"
            }
        },
        "links": {
            "type": "array",
            "default": [],
            "title": "The links Schema",
            "items": {
                "type": "object",
                "title": "A Schema",
                "required": [
                    "dst",
                    "id",
                    "length",
                    "src"
                ],
                "properties": {
                    "dst": {
                        "type": "integer",
                        "title": "The dst Schema"
                    },
                    "id": {
                        "type": "integer",
                        "title": "The id Schema"
                    },
                    "length": {
                        "type": "integer",
                        "title": "The length Schema"
                    },
                    "src": {
                        "type": "integer",
                        "title": "The src Schema"
                    }
                }
            }
        }
    }
}

=== jbcedeno930806/multiband/networks/eurocore/network.json
{
    "alias": "network",
    "Name": "network",
    "nodes": [
        {
            "id": 0
        },
        {
            "id": 1
        },
        {
            "id": 2
        },
        {
            "id": 3
        },
        {
            "id": 4
        },
        {
            "id": 5
        },
        {
            "id": 6
        },
        {
            "id": 7
        },
        {
            "id": 8
        },
        {
            "id": 9
        },
        {
            "id": 10
        }
    ],
    "bands_info": {
        "C": 344,
        "L": 480,
        "S": 760,
        "E": 1136
    },
    "links": [
        {
            "dst": 1,
            "id": 0,
            "length": 525,
            "src": 0
        },
        {
            "dst": 0,
            "id": 1,
            "length": 525,
            "src": 1
        },
        {
            "dst": 5,
            "id": 2,
            "length": 563,
            "src": 0
        },
        {
            "dst": 0,
            "id": 3,
            "length": 563,
            "src": 5
        },
        {
            "dst": 6,
            "id": 4,
            "length": 213,
            "src": 0
        },
        {
            "dst": 0,
            "id": 5,
            "length": 213,
            "src": 6
        },
        {
            "dst": 7,
            "id": 6,
            "length": 725,
            "src": 0
        },
        {
            "dst": 0,
            "id": 7,
            "length": 725,
            "src": 7
        },
        {
            "dst": 2,
            "id": 8,
            "length": 325,
            "src": 1
        },
        {
            "dst": 1,
            "id": 9,
            "length": 325,
            "src": 2
        },
        {
            "dst": 4,
            "id": 10,
            "length": 800,
            "src": 1
        },
        {
            "dst": 1,
            "id": 11,
            "length": 800,
            "src": 4
        },
        {
            "dst": 6,
            "id": 12,
            "length": 475,
            "src": 1
        },
        {
            "dst": 1,
            "id": 13,
            "length": 475,
            "src": 6
        },
        {
            "dst": 7,
            "id": 14,
            "length": 225,
            "src": 1
        },
        {
            "dst": 1,
            "id": 15,
            "length": 225,
            "src": 7
        },
        {
            "dst": 3,
            "id": 16,
            "length": 875,
            "src": 2
        },
        {
            "dst": 2,
            "id": 17,
            "length": 875,
            "src": 3
        },
        {
            "dst": 7,
            "id": 18,
            "length": 275,
            "src": 2
        },
        {
            "dst": 2,
            "id": 19,
            "length": 275,
            "src": 7
        },
        {
            "dst": 8,
            "id": 20,
            "length": 300,
            "src": 2
        },
        {
            "dst": 2,
            "id": 21,
            "length": 300,
            "src": 8
        },
        {
            "dst": 4,
            "id": 22,
            "length": 325,
            "src": 3
        },
        {
            "dst": 3,
            "id": 23,
            "length": 325,
            "src": 4
        },
        {
            "dst": 8,
            "id": 24,
            "length": 575,
            "src": 3
        },
        {
            "dst": 3,
            "id": 25,
            "length": 575,
            "src": 8
        },
        {
            "dst": 10,
            "id": 26,
            "length": 600,
            "src": 3
        },
        {
            "dst": 3,
            "id": 27,
            "length": 600,
            "src": 10
        },
        {
            "dst": 5,
            "id": 28,
            "length": 475,
            "src": 4
        },
        {
            "dst": 4,
            "id": 29,
            "length": 475,
            "src": 5
        },
        {
            "dst": 8,
            "id": 30,
            "length": 525,
            "src": 4
        },
        {
            "dst": 4,
            "id": 31,
            "length": 525,
            "src": 8
        },
        {
            "dst": 10,
            "id": 32,
            "length": 263,
            "src": 4
        },
        {
            "dst": 4,
            "id": 33,
            "length": 263,
            "src": 10
        },
        {
            "dst": 6,
            "id": 34,
            "length": 475,
            "src": 5
        },
        {
            "dst": 5,
            "id": 35,
            "length": 475,
            "src": 6
        },
        {
            "dst": 10,
            "id": 36,
            "length": 225,
            "src": 5
        },
        {
            "dst": 5,
            "id": 37,
            "length": 225,
            "src": 10
        },
        {
            "dst": 9,
            "id": 38,
            "length": 325,
            "src": 6
        },
        {
            "dst": 6,
            "id": 39,
            "length": 325,
            "src": 9
        },
        {
            "dst": 10,
            "id": 40,
            "length": 400,
            "src": 6
        },
        {
            "dst": 6,
            "id": 41,
            "length": 400,
            "src": 10
        },
        {
            "dst": 8,
            "id": 42,
            "length": 175,
            "src": 7
        },
        {
            "dst": 7,
            "id": 43,
            "length": 175,
            "src": 8
        },
        {
            "dst": 9,
            "id": 44,
            "length": 163,
            "src": 7
        },
        {
            "dst": 7,
            "id": 45,
            "length": 163,
            "src": 9
        },
        {
            "dst": 9,
            "id": 46,
            "length": 288,
            "src": 8
        },
        {
            "dst": 8,
            "id": 47,
            "length": 288,
            "src": 9
        },
        {
            "dst": 10,
            "id": 48,
            "length": 525,
            "src": 9
        },
        {
            "dst": 9,
            "id": 49,
            "length": 525,
            "src": 10
        }
    ]
}

=== jbcedeno930806/multiband/scripts/results/nsfnet/network_c.json
{
    "alias": "network",
    "Name": "network",
    "nodes": [
        {
            "id": 0
        },
        {
            "id": 1
        },
        {
            "id": 2
        },
        {
            "id": 3
        },
        {
            "id": 4
        },
        {
            "id": 5
        },
        {
            "id": 6
        },
        {
            "id": 7
        },
        {
            "id": 8
        },
        {
            "id": 9
        },
        {
            "id": 10
        },
        {
            "id": 11
        },
        {
            "id": 12
        },
        {
            "id": 13
        }
    ],
    "bands_info": {
        "C": 344
    },
    "links": [
        {
            "dst": 1,
            "id": 0,
            "length": 1050,
            "src": 0
        },
        {
            "dst": 0,
            "id": 1,
            "length": 1050,
            "src": 1
        },
        {
            "dst": 2,
            "id": 2,
            "length": 1500,
            "src": 0
        },
        {
            "dst": 0,
            "id": 3,
            "length": 1500,
            "src": 2
        },
        {
            "dst": 7,
            "id": 4,
            "length": 2400,
            "src": 0
        },
        {
            "dst": 0,
            "id": 5,
            "length": 2400,
            "src": 7
        },
        {
            "dst": 2,
            "id": 6,
            "length": 600,
            "src": 1
        },
        {
            "dst": 1,
            "id": 7,
            "length": 600,
            "src": 2
        },
        {
            "dst": 3,
            "id": 8,
            "length": 750,
            "src": 1
        },
        {
            "dst": 1,
            "id": 9,
            "length": 750,
            "src": 3
        },
        {
            "dst": 5,
            "id": 10,
            "length": 1800,
            "src": 2
        },
        {
            "dst": 2,
            "id": 11,
            "length": 1800,
            "src": 5
        },
        {
            "dst": 4,
            "id": 12,
            "length": 600,
            "src": 3
        },
        {
            "dst": 3,
            "id": 13,
            "length": 600,
            "src": 4
        },
        {
            "dst": 10,
            "id": 14,
            "length": 1950,
            "src": 3
        },
        {
            "dst": 3,
            "id": 15,
            "length": 1950,
            "src": 10
        },
        {
            "dst": 5,
            "id": 16,
            "length": 1200,
            "src": 4
        },
        {
            "dst": 4,
            "id": 17,
            "length": 1200,
            "src": 5
        },
        {
            "dst": 6,
            "id": 18,
            "length": 600,
            "src": 4
        },
        {
            "dst": 4,
            "id": 19,
            "length": 600,
            "src": 6
        },
        {
            "dst": 9,
            "id": 20,
            "length": 1050,
            "src": 5
        },
        {
            "dst": 5,
            "id": 21,
            "length": 1050,
            "src": 9
        },
        {
            "dst": 13,
            "id": 22,
            "length": 1800,
            "src": 5
        },
        {
            "dst": 5,
            "id": 23,
            "length": 1800,
            "src": 13
        },
        {
            "dst": 7,
            "id": 24,
            "length": 750,
            "src": 6
        },
        {
            "dst": 6,
            "id": 25,
            "length": 750,
            "src": 7
        },
        {
            "dst": 9,
            "id": 26,
            "length": 1350,
            "src": 6
        },
        {
            "dst": 6,
            "id": 27,
            "length": 1350,
            "src": 9
        },
        {
            "dst": 8,
            "id": 28,
            "length": 750,
            "src": 7
        },
        {
            "dst": 7,
            "id": 29,
            "length": 750,
            "src": 8
        },
        {
            "dst": 9,
            "id": 30,
            "length": 750,
            "src": 8
        },
        {
            "dst": 8,
            "id": 31,
            "length": 750,
            "src": 9
        },
        {
            "dst": 11,
            "id": 32,
            "length": 300,
            "src": 8
        },
        {
            "dst": 8,
            "id": 33,
            "length": 300,
            "src": 11
        },
        {
            "dst": 12,
            "id": 34,
            "length": 300,
            "src": 8
        },
        {
            "dst": 8,
            "id": 35,
            "length": 300,
            "src": 12
        },
        {
            "dst": 11,
            "id": 36,
            "length": 600,
            "src": 10
        },
        {
            "dst": 10,
            "id": 37,
            "length": 600,
            "src": 11
        },
        {
            "dst": 12,
            "id": 38,
            "length": 750,
            "src": 10
        },
        {
            "dst": 10,
            "id": 39,
            "length": 750,
            "src": 12
        },
        {
            "dst": 13,
            "id": 40,
            "length": 300,
            "src": 11
        },
        {
            "dst": 11,
            "id": 41,
            "length": 300,
            "src": 13
        },
        {
            "dst": 13,
            "id": 42,
            "length": 150,
            "src": 12
        },
        {
            "dst": 12,
            "id": 43,
            "length": 150,
            "src": 13
        }
    ]
}
